[package]
name = "Connect-Four"
version = "0.1.0"
authors = ["Kai Bailey <kbailey1@ualberta.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
