[package]
name = "connect_four_cli"
version = "0.1.0"
authors = ["dinulade101 <dinulasd@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.rand]
version = "0.6.5"
features = ["stdweb"]
